In [1]:
# Run the command below if necessary, for example with Google Colab
#!python3 -m pip install mxnet-cu117

In [2]:
import mxnet as mx
import numpy as np
import pandas as pd

from sklearn import datasets

In [3]:
# Perceptron Model
def perceptron_with_softmax(weights, bias, features):
    
    output = mx.nd.dot(features, weights) + bias
    return mx.nd.SoftmaxActivation(output)

In [4]:
# Loading data
iris = datasets.load_iris()
iris_df = pd.DataFrame(iris.data, columns = iris.feature_names)
iris_df.insert(0, "class", iris.target)

In [5]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   class              150 non-null    int64  
 1   sepal length (cm)  150 non-null    float64
 2   sepal width (cm)   150 non-null    float64
 3   petal length (cm)  150 non-null    float64
 4   petal width (cm)   150 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [6]:
iris_df.head()

class  sepal length (cm)  sepal width (cm)  petal length (cm)  \
0      0                5.1               3.5                1.4   
1      0                4.9               3.0                1.4   
2      0                4.7               3.2                1.3   
3      0                4.6               3.1                1.5   
4      0                5.0               3.6                1.4   

   petal width (cm)  
0               0.2  
1               0.2  
2               0.2  
3               0.2  
4               0.2

In [7]:
# Number of Features: number of columns of dataframe except output (class)

number_of_features = len(iris_df.columns) - 1
print(number_of_features)

4


In [8]:
# Number of outputs: 3 (different classes)
number_of_outputs = 3

In [9]:
# Model Parameters Definition + Initialization
weights = mx.nd.random_normal(shape=(number_of_features, number_of_outputs))
bias = mx.nd.random_normal(shape=number_of_outputs)
print("Weights:")
print(weights)
print()
print("Bias:")
print(bias)

Weights:

[[ 2.2122064   0.7740038   1.0434403 ]
 [ 1.1839255   1.8917114  -1.2347414 ]
 [-1.771029   -0.45138445  0.57938355]
 [-1.856082   -1.9768796  -0.20801921]]
<NDArray 4x3 @cpu(0)>

Bias:

[ 0.2444218  -0.03716067 -0.48774993]
<NDArray 3 @cpu(0)>


In [10]:
# Input features of an example
example_input = mx.nd.array(iris_df.iloc[0].drop("class").to_numpy())
print(example_input)


[5.1 3.5 1.4 0.2]
<NDArray 4 @cpu(0)>


In [11]:
# Expected output of the example (class)
expected_output = int(iris_df.iloc[0]["class"])
print(expected_output)

0


In [12]:
# Calculate the prediction of our model
model_output = perceptron_with_softmax(weights, bias, example_input).asnumpy()
print(np.argmax(model_output))

0
